name: dio_riverpod_example
description: "Examples for using dio and riverpod in Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  riverpod_generator: ^2.6.3
  riverpod_annotation: ^2.6.1
  cupertino_icons: ^1.0.8
  retrofit: ^4.4.2
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true
